## 1. Introduction
<p>Version control repositories like CVS, Subversion or Git can be a real gold mine for software developers. They contain every change to the source code including the date (the "when"), the responsible developer (the "who"), as well as little message that describes the intention (the "what") of a change.</p>
<p><a href="https://commons.wikimedia.org/wiki/File:Tux.svg">
<img style="float: right;margin:5px 20px 5px 1px" width="150px" src="https://assets.datacamp.com/production/project_111/img/tux.png" alt="Tux - the Linux mascot">
</a></p>
<p>In this notebook, we will analyze the evolution of a very famous open-source project &ndash; the Linux kernel. The Linux kernel is the heart of some Linux distributions like Debian, Ubuntu or CentOS. </p>
<p>We get some first insights into the work of the development efforts by </p>
<ul>
<li>identifying the TOP 10 contributors and</li>
<li>visualizing the commits over the years.</li>
</ul>
<p>Linus Torvalds, the (spoiler alert!) main contributor to the Linux kernel (and also the creator of Git), created a <a href="https://github.com/torvalds/linux/">mirror of the Linux repository on GitHub</a>. It contains the complete history of kernel development for the last 13 years.</p>
<p>For our analysis, we will use a Git log file with the following content:</p>

In [208]:
# Printing the content of git_log_excerpt.csv
# ... YOUR CODE FOR TASK 1 ...
import pandas as pd
pd.read_csv('datasets/git_log_excerpt.csv', header=None, sep='#')

            0                  1
0  1502382966     Linus Torvalds
1  1501368308       Max Gurtovoy
2  1501625560        James Smart
3  1501625559        James Smart
4  1500568442       Martin Wilck
5  1502273719           Xin Long
6  1502278684    Nikolay Borisov
7  1502238384  Girish Moodalbail
8  1502228709   Florian Fainelli
9  1502223836     Jon Paul Maloy

## 2. Reading in the dataset
<p>The dataset was created by using the command <code>git log --encoding=latin-1 --pretty="%at#%aN"</code>. The <code>latin-1</code> encoded text output was saved in a header-less csv file. In this file, each row is a commit entry with the following information:</p>
<ul>
<li><code>timestamp</code>: the time of the commit as a UNIX timestamp in seconds since 1970-01-01 00:00:00 (Git log placeholder "<code>%at</code>")</li>
<li><code>author</code>: the name of the author that performed the commit (Git log placeholder "<code>%aN</code>")</li>
</ul>
<p>The columns are separated by the number sign <code>#</code>. The complete dataset is in the <code>datasets/</code> directory. It is a <code>gz</code>-compressed csv file named <code>git_log.gz</code>.</p>

In [210]:
# Loading in the pandas module
# ... YOUR CODE FOR TASK 2 ...

# Reading in the log file
git_log = pd.read_csv('datasets/git_log.gz', compression = 'gzip', encoding='latin-1', header=None, sep='#')

git_log.columns = ['timestamp', 'author']
git_log.head(5)
# Printing out the first 5 rows
# ... YOUR CODE FOR TASK 2 ...

    timestamp          author
0  1502826583  Linus Torvalds
1  1501749089   Adrian Hunter
2  1501749088   Adrian Hunter
3  1501882480       Kees Cook
4  1497271395       Rob Clark

## 3. Getting an overview
<p>The dataset contains the information about every single code contribution (a "commit") to the Linux kernel over the last 13 years. We'll first take a look at the number of authors and their commits to the repository.</p>

In [212]:
# calculating number of commits
number_of_commits = git_log['timestamp'].count()

# calculating number of authors
number_of_authors = git_log['author'].nunique()

# printing out the results
print("%s authors committed %s code changes." % (number_of_authors, number_of_commits))

17385 authors committed 699071 code changes.

## 4. Finding the TOP 10 contributors
<p>There are some very important people that changed the Linux kernel very often. To see if there are any bottlenecks, we take a look at the TOP 10 authors with the most commits.</p>

In [214]:
# Identifying the top 10 authors
top_10_authors = git_log.groupby('author').count().sort_values('timestamp', ascending= False).head(10)
top_10_authors.columns = ['Count']
# Listing contents of 'top_10_authors'
top_10_authors

                       Count
author
Linus Torvalds         23361
David S. Miller         9106
Mark Brown              6802
Takashi Iwai            6209
Al Viro                 6006
H Hartley Sweeten       5938
Ingo Molnar             5344
Mauro Carvalho Chehab   5204
Arnd Bergmann           4890
Greg Kroah-Hartman      4580

## 5. Wrangling the data
<p>For our analysis, we want to visualize the contributions over time. For this, we use the information in the <code>timestamp</code> column to create a time series-based column.</p>

In [216]:
# converting the timestamp column
# ... YOUR CODE FOR TASK 5 ...
git_log['timestamp'] = pd.to_datetime(git_log['timestamp'], unit='s')
# summarizing the converted timestamp column
# ... YOUR CODE FOR TASK 5 ...
git_log['timestamp'].describe()

count                  699071
unique                 668448
top       2008-09-04 05:30:19
freq                       99
first     1970-01-01 00:00:01
last      2037-04-25 08:08:26
Name: timestamp, dtype: object

## 6. Treating wrong timestamps
<p>As we can see from the results above, some contributors had their operating system's time incorrectly set when they committed to the repository. We'll clean up the <code>timestamp</code> column by dropping the rows with the incorrect timestamps.</p>

In [218]:
# determining the first real commit timestamp
sorted_time = git_log.sort_values('timestamp')
first_commit_timestamp = '2005-04-16 22:20:36'

# determining the last sensible commit timestamp
possible_timestamp = sorted_time.loc[sorted_time['timestamp'] <= '2017-10-03 12:57:00', :].sort_values('timestamp', ascending = False)

last_commit_timestamp = possible_timestamp.iloc[0, 0]
sorted_time = sorted_time.set_index('timestamp')
# filtering out wrong timestamps
corrected_log = sorted_time.loc[first_commit_timestamp:last_commit_timestamp]
sorted_time = sorted_time.reset_index()

corrected_log = corrected_log.reset_index()

# summarizing the corrected timestamp column
# ... YOUR CODE FOR TASK 6 ...
corrected_log['timestamp'].describe()

count                  698569
unique                 667977
top       2008-09-04 05:30:19
freq                       99
first     2005-04-16 22:20:36
last      2017-10-03 12:57:00
Name: timestamp, dtype: object

## 7. Grouping commits per year
<p>To find out how the development activity has increased over time, we'll group the commits by year and count them up.</p>

In [ ]:
# Counting the no. commits per year
commits_per_year = corrected_log.groupby(pd.Grouper(key='timestamp', freq='AS')).count()
# Listing the first rows
# ... YOUR CODE FOR TASK 7 ...
commits_per_year.head(5)

            author
timestamp
2005-01-01   16229
2006-01-01   29255
2007-01-01   33759
2008-01-01   48847
2009-01-01   52572

## 8. Visualizing the history of Linux
<p>Finally, we'll make a plot out of these counts to better see how the development effort on Linux has increased over the the last few years. </p>

In [ ]:
# Setting up plotting in Jupyter notebooks
%matplotlib inline
import matplotlib.pyplot as plt
# plot the data
# ... YOUR CODE FOR TASK 8 ...
commits_per_year.plot(legend=False)
plt.xlabel('Year')
plt.ylabel('Number of Commits')
plt.title('History of Linux')
plt.show()

## 9.  Conclusion
<p>Thanks to the solid foundation and caretaking of Linux Torvalds, many other developers are now able to contribute to the Linux kernel as well. There is no decrease of development activity at sight!</p>

In [ ]:
# calculating or setting the year with the most commits to Linux
year_with_most_commits = commits_per_year['author'].idxmax().year